// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NeonMonolith.Contexts;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace NeonMonolith.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview4.19216.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("NeonMonolith.Models.ResidentialLease", b =>
                {
                    b.Property<long>("Matrix_Unique_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("matrix_unique_id");

                    b.Property<string>("AC")
                        .HasColumnName("ac");

                    b.Property<string>("AccessInstruction")
                        .HasColumnName("access_instruction");

                    b.Property<int?>("ActiveOpenHouseCount")
                        .HasColumnName("active_open_house_count");

                    b.Property<int?>("AdditionalPetFee")
                        .HasColumnName("additional_pet_fee");

                    b.Property<string>("AdditionalPetFeeDescript")
                        .HasColumnName("additional_pet_fee_descript");

                    b.Property<string>("Address")
                        .HasColumnName("address");

                    b.Property<string>("AddressInternet")
                        .HasColumnName("address_internet");

                    b.Property<string>("AdminFeePaybleTo")
                        .HasColumnName("admin_fee_payble_to");

                    b.Property<int?>("AdministrationFee")
                        .HasColumnName("administration_fee");

                    b.Property<bool?>("Allow3rdPartyComments")
                        .HasColumnName("allow_3rd_party_comments");

                    b.Property<bool?>("AllowAutomatedValuations")
                        .HasColumnName("allow_automated_valuations");

                    b.Property<string>("AlsoListedAs")
                        .HasColumnName("also_listed_as");

                    b.Property<string>("AppDeliveryTo")
                        .HasColumnName("app_delivery_to");

                    b.Property<string>("AppDepositPayableTo")
                        .HasColumnName("app_deposit_payable_to");

                    b.Property<string>("AppFeePayableTo")
                        .HasColumnName("app_fee_payable_to");

                    b.Property<string>("AppliancesMaintained")
                        .HasColumnName("appliances_maintained");

                    b.Property<int?>("ApplicationFee")
                        .HasColumnName("application_fee");

                    b.Property<string>("ApplicationPolicy")
                        .HasColumnName("application_policy");

                    b.Property<string>("ApplicationRequired")
                        .HasColumnName("application_required");

                    b.Property<string>("ApplicationRequirements")
                        .HasColumnName("application_requirements");

                    b.Property<string>("Area")
                        .HasColumnName("area");

                    b.Property<string>("AreaAmenities")
                        .HasColumnName("area_amenities");

                    b.Property<int?>("AssociationFee")
                        .HasColumnName("association_fee");

                    b.Property<string>("AssociationFeeFrequency")
                        .HasColumnName("association_fee_frequency");

                    b.Property<DateTime?>("BackOnMarketDate")
                        .HasColumnName("back_on_market_date");

                    b.Property<int?>("BathsFull")
                        .HasColumnName("baths_full");

                    b.Property<int?>("BathsHalf")
                        .HasColumnName("baths_half");

                    b.Property<int?>("BathsTotal")
                        .HasColumnName("baths_total");

                    b.Property<int?>("BedsTotal")
                        .HasColumnName("beds_total");

                    b.Property<string>("BodyofWater")
                        .HasColumnName("body_of_water");

                    b.Property<int?>("CDOM")
                        .HasColumnName("cdom");

                    b.Property<string>("CDOM_ChangeNotes")
                        .HasColumnName("cdom_change_notes");

                    b.Property<int?>("CDOM_Initial")
                        .HasColumnName("cdom_initial");

                    b.Property<bool?>("CDOM_Seed_APN_Match")
                        .HasColumnName("cdom_seed_apn_match");

                    b.Property<bool?>("CDOM_Seed_Address_Match")
                        .HasColumnName("cdom_seed_address_match");

                    b.Property<DateTime?>("CDOM_Seed_Datetime")
                        .HasColumnName("cdom_seed_datetime");

                    b.Property<long?>("CDOM_Seed_Listing_MUI")
                        .HasColumnName("cdom_seed_listing_mui");

                    b.Property<string>("CDOM_Seed_MLNumber")
                        .HasColumnName("cdom_seed_ml_number");

                    b.Property<string>("CeilingFanLocation")
                        .HasColumnName("ceiling_fan_location");

                    b.Property<bool?>("CeilingFanYN")
                        .HasColumnName("ceiling_fan_yn");

                    b.Property<bool?>("CertifiedFunds")
                        .HasColumnName("certified_funds");

                    b.Property<string>("City")
                        .HasColumnName("city");

                    b.Property<DateTime?>("CloseDate")
                        .HasColumnName("close_date");

                    b.Property<decimal?>("ClosePrice")
                        .HasColumnName("close_price");

                    b.Property<string>("CoListAgentDirectWorkPhone")
                        .HasColumnName("co_list_agent_direct_work_phone");

                    b.Property<string>("CoListAgentFullName")
                        .HasColumnName("co_list_agent_full_name");

                    b.Property<string>("CoListAgentMLSID")
                        .HasColumnName("co_list_agent_mls_id");

                    b.Property<long?>("CoListAgent_MUI")
                        .HasColumnName("co_list_agent_mui");

                    b.Property<string>("CoListOfficeMLSID")
                        .HasColumnName("co_list_office_mls_id");

                    b.Property<string>("CoListOfficeName")
                        .HasColumnName("co_list_office_name");

                    b.Property<string>("CoListOfficePhone")
                        .HasColumnName("co_list_office_phone");

                    b.Property<long?>("CoListOffice_MUI")
                        .HasColumnName("co_list_office_mui");

                    b.Property<string>("CoSellingAgentDirectWorkPhone")
                        .HasColumnName("co_selling_agent_direct_work_phone");

                    b.Property<string>("CoSellingAgentFullName")
                        .HasColumnName("co_selling_agent_full_name");

                    b.Property<string>("CoSellingAgentMLSID")
                        .HasColumnName("co_selling_agent_mls_id");

                    b.Property<long?>("CoSellingAgent_MUI")
                        .HasColumnName("co_selling_agent_mui");

                    b.Property<string>("CoSellingOfficeMLSID")
                        .HasColumnName("co_selling_office_mls_id");

                    b.Property<string>("CoSellingOfficeName")
                        .HasColumnName("co_selling_office_name");

                    b.Property<string>("CoSellingOfficePhone")
                        .HasColumnName("co_selling_office_phone");

                    b.Property<long?>("CoSellingOffice_MUI")
                        .HasColumnName("co_selling_office_mui");

                    b.Property<string>("CommunityWebSite")
                        .HasColumnName("community_web_site");

                    b.Property<string>("ComplexName")
                        .HasColumnName("complex_name");

                    b.Property<DateTime?>("ConditionalDate")
                        .HasColumnName("conditional_date");

                    b.Property<string>("Construction")
                        .HasColumnName("construction");

                    b.Property<string>("Country")
                        .HasColumnName("country");

                    b.Property<string>("CountyOrParish")
                        .HasColumnName("county_or_parish");

                    b.Property<int?>("CoveredSpaces")
                        .HasColumnName("covered_spaces");

                    b.Property<bool?>("CreateAutomaticVirtualTourYN")
                        .HasColumnName("create_automatic_virtual_tour_yn");

                    b.Property<decimal?>("CurrentPrice")
                        .HasColumnName("current_price");

                    b.Property<int?>("DOM")
                        .HasColumnName("dom");

                    b.Property<DateTime?>("DatePossession")
                        .HasColumnName("date_possession");

                    b.Property<string>("DiningDescription")
                        .HasColumnName("dining_description");

                    b.Property<string>("Directions")
                        .HasColumnName("directions");

                    b.Property<bool?>("DisabilityFeatures")
                        .HasColumnName("disability_features");

                    b.Property<string>("DisabilityFeaturesDesc")
                        .HasColumnName("disability_features_desc");

                    b.Property<string>("DistanceToUTShuttle")
                        .HasColumnName("distance_to_ut_shuttle");

                    b.Property<string>("DistanceToWaterAccess")
                        .HasColumnName("distance_to_water_access");

                    b.Property<string>("DistancetoLightRail")
                        .HasColumnName("distance_to_light_rail");

                    b.Property<string>("DistancetoMetro")
                        .HasColumnName("distance_to_metro");

                    b.Property<bool?>("DownPaymentResourceYN")
                        .HasColumnName("down_payment_resource_yn");

                    b.Property<string>("Dryer")
                        .HasColumnName("dryer");

                    b.Property<bool?>("DryerMaintained")
                        .HasColumnName("dryer_maintained");

                    b.Property<bool?>("EES")
                        .HasColumnName("ees");

                    b.Property<string>("EESFeatures")
                        .HasColumnName("ees_features");

                    b.Property<string>("ElemAOther")
                        .HasColumnName("elem_a_other");

                    b.Property<string>("ElementaryA")
                        .HasColumnName("elementary_a");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnName("expiration_date");

                    b.Property<string>("ExteriorFeatures")
                        .HasColumnName("exterior_features");

                    b.Property<string>("FEMA100YrFloodPlain")
                        .HasColumnName("fema_100_yr_flood_plain");

                    b.Property<string>("Faces")
                        .HasColumnName("faces");

                    b.Property<string>("FeeDescription")
                        .HasColumnName("fee_description");

                    b.Property<string>("Fence")
                        .HasColumnName("fence");

                    b.Property<bool?>("FenceYN")
                        .HasColumnName("fence_yn");

                    b.Property<string>("FireplaceFeatures")
                        .HasColumnName("fireplace_features");

                    b.Property<string>("FirstMonthRentPayableTo")
                        .HasColumnName("first_month_rent_payable_to");

                    b.Property<string>("FloorPlanNameNumber")
                        .HasColumnName("floor_plan_name_number");

                    b.Property<string>("Flooring")
                        .HasColumnName("flooring");

                    b.Property<string>("FoundationDetails")
                        .HasColumnName("foundation_details");

                    b.Property<string>("Furnished")
                        .HasColumnName("furnished");

                    b.Property<bool?>("GatedCommunity")
                        .HasColumnName("gated_community");

                    b.Property<string>("Gr9HighOther")
                        .HasColumnName("gr9_high_other");

                    b.Property<string>("Gr9HighSchool")
                        .HasColumnName("gr9_high_school");

                    b.Property<string>("GreenRatingProgram")
                        .HasColumnName("green_rating_program");

                    b.Property<int?>("HERSIndex")
                        .HasColumnName("hers_index");

                    b.Property<int?>("HERSYear")
                        .HasColumnName("hers_year");

                    b.Property<string>("HOAName")
                        .HasColumnName("hoa_name");

                    b.Property<string>("HOARequirement")
                        .HasColumnName("hoa_requirement");

                    b.Property<bool?>("HOAYN")
                        .HasColumnName("hoa_yn");

                    b.Property<string>("Heating")
                        .HasColumnName("heating");

                    b.Property<bool?>("Horses")
                        .HasColumnName("horses");

                    b.Property<bool?>("IDXOptInYN")
                        .HasColumnName("idx_opt_in_yn");

                    b.Property<string>("InteriorFeatures")
                        .HasColumnName("interior_features");

                    b.Property<string>("InvoiceSubmission")
                        .HasColumnName("invoice_submission");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Kitchen")
                        .HasColumnName("kitchen");

                    b.Property<string>("KitchenAppliances")
                        .HasColumnName("kitchen_appliances");

                    b.Property<decimal?>("LandSQFT")
                        .HasColumnName("land_sqft");

                    b.Property<DateTime?>("LastChangeTimestamp")
                        .HasColumnName("last_change_timestamp");

                    b.Property<string>("LastChangeType")
                        .HasColumnName("last_change_type");

                    b.Property<decimal?>("LastListPrice")
                        .HasColumnName("last_list_price");

                    b.Property<string>("LastStatus")
                        .HasColumnName("last_status");

                    b.Property<decimal?>("Latitude")
                        .HasColumnName("latitude");

                    b.Property<string>("LaundryFacilities")
                        .HasColumnName("laundry_facilities");

                    b.Property<bool?>("LeaseGuarantor")
                        .HasColumnName("lease_guarantor");

                    b.Property<string>("LegalDescription")
                        .HasColumnName("legal_description");

                    b.Property<string>("ListAgentDirectWorkPhone")
                        .HasColumnName("list_agent_direct_work_phone");

                    b.Property<string>("ListAgentFullName")
                        .HasColumnName("list_agent_full_name");

                    b.Property<string>("ListAgentMLSID")
                        .HasColumnName("list_agent_mls_id");

                    b.Property<long?>("ListAgent_MUI")
                        .HasColumnName("list_agent_mui");

                    b.Property<string>("ListOfficeMLSID")
                        .HasColumnName("list_office_mls_id");

                    b.Property<string>("ListOfficeName")
                        .HasColumnName("list_office_name");

                    b.Property<string>("ListOfficePhone")
                        .HasColumnName("list_office_phone");

                    b.Property<long?>("ListOffice_MUI")
                        .HasColumnName("list_office_mui");

                    b.Property<decimal?>("ListPrice")
                        .HasColumnName("list_price");

                    b.Property<string>("ListingAgentFax")
                        .HasColumnName("listing_agent_fax");

                    b.Property<DateTime?>("ListingContractDate")
                        .HasColumnName("listing_contract_date");

                    b.Property<string>("ListingWillAppearOn")
                        .HasColumnName("listing_will_appear_on");

                    b.Property<string>("LockboxLocation")
                        .HasColumnName("lockbox_location");

                    b.Property<string>("LockboxType")
                        .HasColumnName("lockbox_type");

                    b.Property<decimal?>("Longitude")
                        .HasColumnName("longitude");

                    b.Property<string>("LotFeatures")
                        .HasColumnName("lot_features");

                    b.Property<decimal?>("LotSizeArea")
                        .HasColumnName("lot_size_area");

                    b.Property<string>("LotSizeDimensions")
                        .HasColumnName("lot_size_dimensions");

                    b.Property<string>("LseLengthNegotiable")
                        .HasColumnName("lse_length_negotiable");

                    b.Property<string>("MAPSCOGrid")
                        .HasColumnName("mapsco_grid");

                    b.Property<string>("MAPSCOPage")
                        .HasColumnName("mapsco_page");

                    b.Property<string>("MLNumtobeCopied")
                        .HasColumnName("ml_num_to_be_copied");

                    b.Property<string>("MLS")
                        .HasColumnName("mls");

                    b.Property<string>("MLSNumber")
                        .HasColumnName("mls_number");

                    b.Property<string>("ManagedBy")
                        .HasColumnName("managed_by");

                    b.Property<string>("MasterDescription")
                        .HasColumnName("master_description");

                    b.Property<bool?>("MasterMain")
                        .HasColumnName("master_main");

                    b.Property<DateTime>("MatrixModifiedDT")
                        .HasColumnName("matrix_modified_dt");

                    b.Property<int?>("MaxLeaseMonths")
                        .HasColumnName("max_lease_months");

                    b.Property<int?>("MaxNumofPets")
                        .HasColumnName("max_numof_pets");

                    b.Property<string>("MemberOfficePhoneExt")
                        .HasColumnName("member_office_phone_ext");

                    b.Property<string>("MeterDescription")
                        .HasColumnName("meter_description");

                    b.Property<string>("MgmtCompany")
                        .HasColumnName("mgmt_company");

                    b.Property<string>("MiddleIntermediateSchool")
                        .HasColumnName("middle_intermediate_school");

                    b.Property<string>("MiddleOther")
                        .HasColumnName("middle_other");

                    b.Property<int?>("MinLeaseMonths")
                        .HasColumnName("min_lease_months");

                    b.Property<int?>("MonthlyPetRent")
                        .HasColumnName("monthly_pet_rent");

                    b.Property<bool?>("MonthlyPetRentPerPetYN")
                        .HasColumnName("monthly_pet_rent_per_pet_yn");

                    b.Property<string>("MoveInRequirements")
                        .HasColumnName("move_in_requirements");

                    b.Property<string>("MoveInSpecialDescription")
                        .HasColumnName("move_in_special_description");

                    b.Property<bool?>("MoveInSpecialYN")
                        .HasColumnName("move_in_special_yn");

                    b.Property<int?>("NumBlockstoMetroLightrail")
                        .HasColumnName("num_blocks_to_metro_lightrail");

                    b.Property<int?>("NumBlockstoUTShuttle")
                        .HasColumnName("num_blocks_to_ut_shuttle");

                    b.Property<int?>("NumDining")
                        .HasColumnName("num_dining");

                    b.Property<int?>("NumFireplaces")
                        .HasColumnName("num_fireplaces");

                    b.Property<int?>("NumHorsesAllowed")
                        .HasColumnName("num_horses_allowed");

                    b.Property<int?>("NumLiving")
                        .HasColumnName("num_living");

                    b.Property<int?>("NumMainLevelBeds")
                        .HasColumnName("num_main_level_beds");

                    b.Property<int?>("NumOtherLevelBeds")
                        .HasColumnName("num_other_level_beds");

                    b.Property<int?>("NumParkingSpaces")
                        .HasColumnName("num_parking_spaces");

                    b.Property<int?>("NumberOfUnitsInComplex")
                        .HasColumnName("number_of_units_in_complex");

                    b.Property<string>("OccupantName")
                        .HasColumnName("occupant_name");

                    b.Property<string>("OccupantPhone")
                        .HasColumnName("occupant_phone");

                    b.Property<string>("OccupantPhoneOther")
                        .HasColumnName("occupant_phone_other");

                    b.Property<string>("OccupantType")
                        .HasColumnName("occupant_type");

                    b.Property<DateTime?>("OffMarketDate")
                        .HasColumnName("off_market_date");

                    b.Property<bool?>("OnSiteComplianceYN")
                        .HasColumnName("on_site_compliance_yn");

                    b.Property<string>("OneTimeExpenses")
                        .HasColumnName("one_time_expenses");

                    b.Property<string>("OnlineAppInstructions")
                        .HasColumnName("online_app_instructions");

                    b.Property<string>("OnlineAppInstructionspublic")
                        .HasColumnName("online_app_instructionspublic");

                    b.Property<int?>("OpenHouseCount")
                        .HasColumnName("open_house_count");

                    b.Property<DateTime?>("OpenHouseDatepublic")
                        .HasColumnName("open_house_date_public");

                    b.Property<string>("OpenHouseTimePublic")
                        .HasColumnName("open_house_time_public");

                    b.Property<string>("OpenHouseUpcoming")
                        .HasColumnName("open_house_upcoming");

                    b.Property<DateTime?>("OriginalEntryTimestamp")
                        .HasColumnName("original_entry_timestamp");

                    b.Property<decimal?>("OriginalListPrice")
                        .HasColumnName("original_list_price");

                    b.Property<string>("OutdoorLivingFeatures")
                        .HasColumnName("outdoor_living_features");

                    b.Property<string>("OutofAreaCity")
                        .HasColumnName("out_of_area_city");

                    b.Property<string>("OutofAreaCounty")
                        .HasColumnName("out_of_area_county");

                    b.Property<string>("OutofAreaSchoolDistrict")
                        .HasColumnName("out_of_area_school_district");

                    b.Property<string>("OwnerName")
                        .HasColumnName("owner_name");

                    b.Property<string>("OwnerPays")
                        .HasColumnName("owner_pays");

                    b.Property<string>("OwnerPhone")
                        .HasColumnName("owner_phone");

                    b.Property<string>("ParcelNumber")
                        .HasColumnName("parcel_number");

                    b.Property<string>("ParkingFeatures")
                        .HasColumnName("parking_features");

                    b.Property<string>("ParkingFeeFrequency")
                        .HasColumnName("parking_fee_frequency");

                    b.Property<int?>("ParkingFeeFrom")
                        .HasColumnName("parking_fee_from");

                    b.Property<int?>("ParkingFeeTo")
                        .HasColumnName("parking_fee_to");

                    b.Property<DateTime?>("PendingDate")
                        .HasColumnName("pending_date");

                    b.Property<bool?>("PerPerson")
                        .HasColumnName("per_person");

                    b.Property<bool?>("PerPet")
                        .HasColumnName("per_pet");

                    b.Property<bool?>("PermitInternetYN")
                        .HasColumnName("permit_internet_yn");

                    b.Property<int?>("PetDeposit")
                        .HasColumnName("pet_deposit");

                    b.Property<string>("PetDescription")
                        .HasColumnName("pet_description");

                    b.Property<bool?>("Pets")
                        .HasColumnName("pets");

                    b.Property<int?>("PhotoCount")
                        .HasColumnName("photo_count");

                    b.Property<string>("PhotoExist")
                        .HasColumnName("photo_exist");

                    b.Property<DateTime?>("PhotoModificationTimestamp")
                        .HasColumnName("photo_modification_timestamp");

                    b.Property<string>("PoolDescronProp")
                        .HasColumnName("pool_descr_on_prop");

                    b.Property<bool?>("PoolonProperty")
                        .HasColumnName("pool_on_property");

                    b.Property<string>("PostalCode")
                        .HasColumnName("postal_code");

                    b.Property<string>("PostalCodePlus4")
                        .HasColumnName("postal_code_plus4");

                    b.Property<DateTime?>("PriceChangeTimestamp")
                        .HasColumnName("price_change_timestamp");

                    b.Property<string>("PrivateRemarks")
                        .HasColumnName("private_remarks");

                    b.Property<bool?>("PropertyAddressonInternet")
                        .HasColumnName("property_address_on_internet");

                    b.Property<string>("PropertySubType")
                        .HasColumnName("property_sub_type");

                    b.Property<string>("PropertyType")
                        .HasColumnName("property_type");

                    b.Property<int?>("ProviderKey")
                        .HasColumnName("provider_key");

                    b.Property<string>("PublicRemarks")
                        .HasColumnName("public_remarks");

                    b.Property<decimal?>("RATIO_ClosePrice_By_ListPrice")
                        .HasColumnName("ratio_close_price_by_list_price");

                    b.Property<decimal?>("RATIO_ClosePrice_By_OriginalListPrice")
                        .HasColumnName("ratio_close_price_by_original_list_price");

                    b.Property<decimal?>("RATIO_ClosePrice_By_SQFT")
                        .HasColumnName("ratio_close_price_by_sqft");

                    b.Property<decimal?>("RATIO_CurrentPrice_By_SQFT")
                        .HasColumnName("ratio_current_price_by_sqft");

                    b.Property<decimal?>("RATIO_ListPrice_By_SQFT")
                        .HasColumnName("ratio_list_price_by_sqft");

                    b.Property<string>("Range")
                        .HasColumnName("range");

                    b.Property<string>("RatingAchieved")
                        .HasColumnName("rating_achieved");

                    b.Property<int?>("RatingYear")
                        .HasColumnName("rating_year");

                    b.Property<string>("RecurringExpenses")
                        .HasColumnName("recurring_expenses");

                    b.Property<bool?>("Refrigerator")
                        .HasColumnName("refrigerator");

                    b.Property<bool?>("RefrigeratorMaintained")
                        .HasColumnName("refrigerator_maintained");

                    b.Property<string>("Region")
                        .HasColumnName("region");

                    b.Property<bool?>("RentersInsuranceRequiredYN")
                        .HasColumnName("renters_insurance_required_yn");

                    b.Property<string>("ReqdDocAgentInfor")
                        .HasColumnName("reqd_doc_agent_infor");

                    b.Property<string>("Roof")
                        .HasColumnName("roof");

                    b.Property<string>("Rooms")
                        .HasColumnName("rooms");

                    b.Property<string>("SchoolDistrict")
                        .HasColumnName("school_district");

                    b.Property<DateTime?>("SearchExpireDate")
                        .HasColumnName("search_expire_date");

                    b.Property<bool?>("Section8")
                        .HasColumnName("section8");

                    b.Property<int?>("SecurityDeposit")
                        .HasColumnName("security_deposit");

                    b.Property<string>("SellingAgentDirectWorkPhone")
                        .HasColumnName("selling_agent_direct_work_phone");

                    b.Property<string>("SellingAgentFullName")
                        .HasColumnName("selling_agent_full_name");

                    b.Property<string>("SellingAgentMLSID")
                        .HasColumnName("selling_agent_mls_id");

                    b.Property<long?>("SellingAgent_MUI")
                        .HasColumnName("selling_agent_mui");

                    b.Property<string>("SellingOfficeMLSID")
                        .HasColumnName("selling_office_mls_id");

                    b.Property<string>("SellingOfficeName")
                        .HasColumnName("selling_office_name");

                    b.Property<string>("SellingOfficePhone")
                        .HasColumnName("selling_office_phone");

                    b.Property<long?>("SellingOffice_MUI")
                        .HasColumnName("selling_office_mui");

                    b.Property<string>("SeniorHighSchool")
                        .HasColumnName("senior_high_school");

                    b.Property<string>("Sewer")
                        .HasColumnName("sewer");

                    b.Property<decimal?>("ShortTermPremiumAmount")
                        .HasColumnName("short_term_premium_amount");

                    b.Property<bool?>("ShortTermPremiumYN")
                        .HasColumnName("short_term_premium_yn");

                    b.Property<bool?>("SmokingInside")
                        .HasColumnName("smoking_inside");

                    b.Property<string>("SoldLeasedComments")
                        .HasColumnName("sold_leased_comments");

                    b.Property<string>("SoldTerms")
                        .HasColumnName("sold_terms");

                    b.Property<string>("SpaHotTubDescription")
                        .HasColumnName("spa_hot_tub_description");

                    b.Property<bool?>("SpaHotTubYN")
                        .HasColumnName("spa_hot_tub_yn");

                    b.Property<bool?>("SprinklerSystem")
                        .HasColumnName("sprinkler_system");

                    b.Property<int?>("SqftTotal")
                        .HasColumnName("sqft_total");

                    b.Property<string>("SquareFootSource")
                        .HasColumnName("square_foot_source");

                    b.Property<string>("SrHighOther")
                        .HasColumnName("sr_high_other");

                    b.Property<string>("StateOrProvince")
                        .HasColumnName("state_or_province");

                    b.Property<string>("Status")
                        .HasColumnName("status");

                    b.Property<DateTime?>("StatusChangeTimestamp")
                        .HasColumnName("status_change_timestamp");

                    b.Property<DateTime?>("StatusContractualSearchDate")
                        .HasColumnName("status_contractual_search_date");

                    b.Property<string>("Steps")
                        .HasColumnName("steps");

                    b.Property<string>("StoriesLookup")
                        .HasColumnName("stories_lookup");

                    b.Property<string>("StreetDirPrefix")
                        .HasColumnName("street_dir_prefix");

                    b.Property<string>("StreetDirSuffix")
                        .HasColumnName("street_dir_suffix");

                    b.Property<string>("StreetName")
                        .HasColumnName("street_name");

                    b.Property<string>("StreetNumber")
                        .HasColumnName("street_number");

                    b.Property<string>("StreetSuffix")
                        .HasColumnName("street_suffix");

                    b.Property<string>("SubdivisionName")
                        .HasColumnName("subdivision_name");

                    b.Property<string>("TaxBlock")
                        .HasColumnName("tax_block");

                    b.Property<int?>("TaxFilledSqftTotal")
                        .HasColumnName("tax_filled_sqft_total");

                    b.Property<string>("TaxLot")
                        .HasColumnName("tax_lot");

                    b.Property<DateTime?>("TempOffMarketDate")
                        .HasColumnName("temp_off_market_date");

                    b.Property<string>("TenantPays")
                        .HasColumnName("tenant_pays");

                    b.Property<DateTime?>("TentativeCloseDate")
                        .HasColumnName("tentative_close_date");

                    b.Property<string>("TransactionType")
                        .HasColumnName("transaction_type");

                    b.Property<string>("Trees")
                        .HasColumnName("trees");

                    b.Property<int?>("UnitCount")
                        .HasColumnName("unit_count");

                    b.Property<string>("UnitNumber")
                        .HasColumnName("unit_number");

                    b.Property<string>("UnitStyle")
                        .HasColumnName("unit_style");

                    b.Property<string>("UpgradedEEFeatures")
                        .HasColumnName("upgraded_ee_features");

                    b.Property<bool?>("UpgradedEnergyEfficient")
                        .HasColumnName("upgraded_energy_efficient");

                    b.Property<string>("Utilities")
                        .HasColumnName("utilities");

                    b.Property<string>("VideoTourLinkBranded")
                        .HasColumnName("video_tour_link_branded");

                    b.Property<string>("VideoTourLinkUnbranded")
                        .HasColumnName("video_tour_link_unbranded");

                    b.Property<string>("View")
                        .HasColumnName("view");

                    b.Property<string>("VirtualTourLinkBranded")
                        .HasColumnName("virtual_tour_link_branded");

                    b.Property<string>("VirtualTourURLUnbranded")
                        .HasColumnName("virtual_tour_url_unbranded");

                    b.Property<string>("Washer")
                        .HasColumnName("washer");

                    b.Property<bool?>("WasherMaintained")
                        .HasColumnName("washer_maintained");

                    b.Property<bool?>("WaterAccess")
                        .HasColumnName("water_access");

                    b.Property<string>("WaterAccessDescription")
                        .HasColumnName("water_access_description");

                    b.Property<string>("WaterSource")
                        .HasColumnName("water_source");

                    b.Property<bool?>("Waterfront")
                        .HasColumnName("waterfront");

                    b.Property<string>("WaterfrontDescription")
                        .HasColumnName("waterfront_description");

                    b.Property<DateTime?>("WithdrawnDate")
                        .HasColumnName("withdrawn_date");

                    b.Property<int?>("YearBuilt")
                        .HasColumnName("year_built");

                    b.Property<string>("YearBuiltException")
                        .HasColumnName("year_built_exception");

                    b.HasKey("Matrix_Unique_ID");

                    b.ToTable("residential_leases");
                });

            modelBuilder.Entity("NeonMonolith.Models.ResidentialProperty", b =>
                {
                    b.Property<long>("Matrix_Unique_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("matrix_unique_id");

                    b.Property<string>("AC")
                        .HasColumnName("ac");

                    b.Property<int?>("ActiveOpenHouseCount")
                        .HasColumnName("active_open_house_count");

                    b.Property<decimal?>("ActualTax")
                        .HasColumnName("actual_tax");

                    b.Property<string>("Address")
                        .HasColumnName("address");

                    b.Property<string>("AddressInternet")
                        .HasColumnName("address_internet");

                    b.Property<bool?>("Allow3rdPartyComments")
                        .HasColumnName("allow_3rd_party_comments");

                    b.Property<bool?>("AllowAutomatedValuations")
                        .HasColumnName("allow_automated_valuations");

                    b.Property<string>("AlsoListedAs")
                        .HasColumnName("also_listed_as");

                    b.Property<int?>("AppraisalAmount")
                        .HasColumnName("appraisal_amount");

                    b.Property<string>("Area")
                        .HasColumnName("area");

                    b.Property<string>("AreaAmenities")
                        .HasColumnName("area_amenities");

                    b.Property<int?>("AssociationFee")
                        .HasColumnName("association_fee");

                    b.Property<string>("AssociationFeeFrequency")
                        .HasColumnName("association_fee_frequency");

                    b.Property<string>("AssociationFeeIncludes")
                        .HasColumnName("association_fee_includes");

                    b.Property<DateTime?>("AuctionDate")
                        .HasColumnName("auction_date");

                    b.Property<bool?>("AuctionYN")
                        .HasColumnName("auction_yn");

                    b.Property<DateTime?>("BackOnMarketDate")
                        .HasColumnName("back_on_market_date");

                    b.Property<int?>("BathsFull")
                        .HasColumnName("baths_full");

                    b.Property<int?>("BathsHalf")
                        .HasColumnName("baths_half");

                    b.Property<int?>("BathsTotal")
                        .HasColumnName("baths_total");

                    b.Property<int?>("BedsTotal")
                        .HasColumnName("beds_total");

                    b.Property<string>("BodyofWater")
                        .HasColumnName("body_of_water");

                    b.Property<string>("BuilderName")
                        .HasColumnName("builder_name");

                    b.Property<int?>("BuyersClsgCostPdbySell")
                        .HasColumnName("buyers_clsg_cost_pdby_sell");

                    b.Property<int?>("CDOM")
                        .HasColumnName("cdom");

                    b.Property<string>("CDOM_ChangeNotes")
                        .HasColumnName("cdom_change_notes");

                    b.Property<int?>("CDOM_Initial")
                        .HasColumnName("cdom_initial");

                    b.Property<bool?>("CDOM_Seed_APN_Match")
                        .HasColumnName("cdom_seed_apn_match");

                    b.Property<bool?>("CDOM_Seed_Address_Match")
                        .HasColumnName("cdom_seed_address_match");

                    b.Property<DateTime?>("CDOM_Seed_Datetime")
                        .HasColumnName("cdom_seed_datetime");

                    b.Property<long?>("CDOM_Seed_Listing_MUI")
                        .HasColumnName("cdom_seed_listing_mui");

                    b.Property<string>("CDOM_Seed_MLNumber")
                        .HasColumnName("cdom_seed_ml_number");

                    b.Property<string>("City")
                        .HasColumnName("city");

                    b.Property<DateTime?>("CloseDate")
                        .HasColumnName("close_date");

                    b.Property<decimal?>("ClosePrice")
                        .HasColumnName("close_price");

                    b.Property<string>("CoListAgentDirectWorkPhone")
                        .HasColumnName("co_list_agent_direct_work_phone");

                    b.Property<string>("CoListAgentFullName")
                        .HasColumnName("co_list_agent_full_name");

                    b.Property<string>("CoListAgentMLSID")
                        .HasColumnName("co_list_agent_mls_id");

                    b.Property<long?>("CoListAgent_MUI")
                        .HasColumnName("co_list_agent_mui");

                    b.Property<string>("CoListOfficeMLSID")
                        .HasColumnName("co_list_office_mls_id");

                    b.Property<string>("CoListOfficeName")
                        .HasColumnName("co_list_office_name");

                    b.Property<string>("CoListOfficePhone")
                        .HasColumnName("co_list_office_phone");

                    b.Property<long?>("CoListOffice_MUI")
                        .HasColumnName("co_list_office_mui");

                    b.Property<string>("CoSellingAgentDirectWorkPhone")
                        .HasColumnName("co_selling_agent_direct_work_phone");

                    b.Property<string>("CoSellingAgentFullName")
                        .HasColumnName("co_selling_agent_full_name");

                    b.Property<string>("CoSellingAgentMLSID")
                        .HasColumnName("co_selling_agent_mls_id");

                    b.Property<long?>("CoSellingAgent_MUI")
                        .HasColumnName("co_selling_agent_mui");

                    b.Property<string>("CoSellingOfficeMLSID")
                        .HasColumnName("co_selling_office_mls_id");

                    b.Property<string>("CoSellingOfficeName")
                        .HasColumnName("co_selling_office_name");

                    b.Property<string>("CoSellingOfficePhone")
                        .HasColumnName("co_selling_office_phone");

                    b.Property<long?>("CoSellingOffice_MUI")
                        .HasColumnName("co_selling_office_mui");

                    b.Property<string>("CommunityWebSite")
                        .HasColumnName("community_web_site");

                    b.Property<DateTime?>("ConditionalDate")
                        .HasColumnName("conditional_date");

                    b.Property<string>("Construction")
                        .HasColumnName("construction");

                    b.Property<string>("Country")
                        .HasColumnName("country");

                    b.Property<string>("CountyOrParish")
                        .HasColumnName("county_or_parish");

                    b.Property<int?>("CoveredSpaces")
                        .HasColumnName("covered_spaces");

                    b.Property<bool?>("CreateAutomaticVirtualTourYN")
                        .HasColumnName("create_automatic_virtual_tour_yn");

                    b.Property<decimal?>("CurrentPrice")
                        .HasColumnName("current_price");

                    b.Property<int?>("DOM")
                        .HasColumnName("dom");

                    b.Property<string>("DiningDescription")
                        .HasColumnName("dining_description");

                    b.Property<string>("Directions")
                        .HasColumnName("directions");

                    b.Property<bool?>("DisabilityFeatures")
                        .HasColumnName("disability_features");

                    b.Property<string>("DisabilityFeaturesDesc")
                        .HasColumnName("disability_features_desc");

                    b.Property<string>("DistanceToUTShuttle")
                        .HasColumnName("distance_to_ut_shuttle");

                    b.Property<string>("DistanceToWaterAccess")
                        .HasColumnName("distance_to_water_access");

                    b.Property<string>("DistancetoLightRail")
                        .HasColumnName("distance_to_light_rail");

                    b.Property<string>("DistancetoMetro")
                        .HasColumnName("distance_to_metro");

                    b.Property<bool?>("DownPaymentResourceYN")
                        .HasColumnName("down_payment_resource_yn");

                    b.Property<bool?>("EES")
                        .HasColumnName("ees");

                    b.Property<string>("EESFeatures")
                        .HasColumnName("ees_features");

                    b.Property<string>("ETJ")
                        .HasColumnName("etj");

                    b.Property<string>("ElemAOther")
                        .HasColumnName("elem_a_other");

                    b.Property<string>("ElementaryA")
                        .HasColumnName("elementary_a");

                    b.Property<string>("Exclusions")
                        .HasColumnName("exclusions");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnName("expiration_date");

                    b.Property<string>("ExteriorFeatures")
                        .HasColumnName("exterior_features");

                    b.Property<string>("FEMA100YrFloodPlain")
                        .HasColumnName("fema_100_yr_flood_plain");

                    b.Property<string>("Faces")
                        .HasColumnName("faces");

                    b.Property<string>("Fence")
                        .HasColumnName("fence");

                    b.Property<bool?>("FenceYN")
                        .HasColumnName("fence_yn");

                    b.Property<string>("FireplaceFeatures")
                        .HasColumnName("fireplace_features");

                    b.Property<string>("Flooring")
                        .HasColumnName("flooring");

                    b.Property<bool?>("ForeclosureREO")
                        .HasColumnName("foreclosure_reo");

                    b.Property<string>("ForeclosureREOType")
                        .HasColumnName("foreclosure_reo_type");

                    b.Property<string>("FoundationDetails")
                        .HasColumnName("foundation_details");

                    b.Property<string>("GADescription")
                        .HasColumnName("ga_description");

                    b.Property<bool?>("GatedCommunity")
                        .HasColumnName("gated_community");

                    b.Property<string>("Gr9HighOther")
                        .HasColumnName("gr9_high_other");

                    b.Property<string>("Gr9HighSchool")
                        .HasColumnName("gr9_high_school");

                    b.Property<string>("GreenRatingProgram")
                        .HasColumnName("green_rating_program");

                    b.Property<bool?>("GuestAccommodations")
                        .HasColumnName("guest_accomodations");

                    b.Property<int?>("HERSIndex")
                        .HasColumnName("hers_index");

                    b.Property<int?>("HERSYear")
                        .HasColumnName("hers_year");

                    b.Property<string>("HOAManagementCo")
                        .HasColumnName("hoa_management_co");

                    b.Property<string>("HOAName")
                        .HasColumnName("hoa_name");

                    b.Property<string>("HOARequirement")
                        .HasColumnName("hoa_requirement");

                    b.Property<int?>("HOATransferFee")
                        .HasColumnName("hoa_transfer_fee");

                    b.Property<bool?>("HOAYN")
                        .HasColumnName("hoa_yn");

                    b.Property<string>("Heating")
                        .HasColumnName("heating");

                    b.Property<bool?>("Horses")
                        .HasColumnName("horses");

                    b.Property<bool?>("IDXOptInYN")
                        .HasColumnName("idx_opt_in_yn");

                    b.Property<string>("InteriorFeatures")
                        .HasColumnName("interior_features");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Kitchen")
                        .HasColumnName("kitchen");

                    b.Property<string>("KitchenAppliances")
                        .HasColumnName("kitchen_appliances");

                    b.Property<decimal?>("LandSQFT")
                        .HasColumnName("land_sqft");

                    b.Property<DateTime?>("LastChangeTimestamp")
                        .HasColumnName("last_change_timestamp");

                    b.Property<string>("LastChangeType")
                        .HasColumnName("last_change_type");

                    b.Property<decimal?>("LastListPrice")
                        .HasColumnName("last_list_price");

                    b.Property<string>("LastStatus")
                        .HasColumnName("last_status");

                    b.Property<decimal?>("Latitude")
                        .HasColumnName("latitude");

                    b.Property<string>("LaundryFacilities")
                        .HasColumnName("laundry_facilities");

                    b.Property<string>("LegalDescription")
                        .HasColumnName("legal_description");

                    b.Property<string>("ListAgentDirectWorkPhone")
                        .HasColumnName("list_agent_direct_work_phone");

                    b.Property<string>("ListAgentFullName")
                        .HasColumnName("list_agent_full_name");

                    b.Property<string>("ListAgentMLSID")
                        .HasColumnName("list_agent_mls_id");

                    b.Property<long?>("ListAgent_MUI")
                        .HasColumnName("list_agent_mui");

                    b.Property<string>("ListOfficeMLSID")
                        .HasColumnName("list_office_mls_id");

                    b.Property<string>("ListOfficeName")
                        .HasColumnName("list_office_name");

                    b.Property<string>("ListOfficePhone")
                        .HasColumnName("list_office_phone");

                    b.Property<long?>("ListOffice_MUI")
                        .HasColumnName("list_office_mui");

                    b.Property<decimal?>("ListPrice")
                        .HasColumnName("list_price");

                    b.Property<string>("ListingAgentFax")
                        .HasColumnName("listing_agent_fax");

                    b.Property<DateTime?>("ListingContractDate")
                        .HasColumnName("listing_contract_date");

                    b.Property<string>("ListingFinancing")
                        .HasColumnName("listing_financing");

                    b.Property<string>("ListingOfficeFax")
                        .HasColumnName("listing_office_fax");

                    b.Property<string>("ListingWillAppearOn")
                        .HasColumnName("listing_will_appear_on");

                    b.Property<decimal?>("Longitude")
                        .HasColumnName("longitude");

                    b.Property<string>("LotFeatures")
                        .HasColumnName("lot_features");

                    b.Property<decimal?>("LotSizeArea")
                        .HasColumnName("lot_size_area");

                    b.Property<string>("LotSizeDimensions")
                        .HasColumnName("lot_size_dimensions");

                    b.Property<string>("MAPSCOGrid")
                        .HasColumnName("mapsco_grid");

                    b.Property<string>("MAPSCOPage")
                        .HasColumnName("mapsco_page");

                    b.Property<string>("MLNumtobeCopied")
                        .HasColumnName("ml_num_to_be_copied");

                    b.Property<string>("MLS")
                        .HasColumnName("mls");

                    b.Property<string>("MLSNumber")
                        .HasColumnName("mls_number");

                    b.Property<string>("MasterDescription")
                        .HasColumnName("master_description");

                    b.Property<bool?>("MasterMain")
                        .HasColumnName("master_main");

                    b.Property<DateTime>("MatrixModifiedDT")
                        .HasColumnName("matrix_modified_dt");

                    b.Property<string>("MiddleIntermediateSchool")
                        .HasColumnName("middle_intermediate_school");

                    b.Property<string>("MiddleOther")
                        .HasColumnName("middle_other");

                    b.Property<int?>("NumBlockstoMetroLightrail")
                        .HasColumnName("num_blocks_to_metro_lightrail");

                    b.Property<int?>("NumBlockstoUTShuttle")
                        .HasColumnName("num_blocks_to_ut_shuttle");

                    b.Property<int?>("NumDining")
                        .HasColumnName("num_dining");

                    b.Property<int?>("NumFireplaces")
                        .HasColumnName("num_fireplaces");

                    b.Property<int?>("NumGuestBeds")
                        .HasColumnName("num_guest_beds");

                    b.Property<int?>("NumGuestFullBaths")
                        .HasColumnName("num_guest_full_baths");

                    b.Property<int?>("NumGuestHalfBaths")
                        .HasColumnName("num_guest_half_baths");

                    b.Property<int?>("NumHorsesAllowed")
                        .HasColumnName("num_horses_allowed");

                    b.Property<int?>("NumLiving")
                        .HasColumnName("num_living");

                    b.Property<int?>("NumMainLevelBeds")
                        .HasColumnName("num_main_level_beds");

                    b.Property<int?>("NumOtherLevelBeds")
                        .HasColumnName("num_other_level_beds");

                    b.Property<int?>("NumParkingSpaces")
                        .HasColumnName("num_parking_spaces");

                    b.Property<DateTime?>("OffMarketDate")
                        .HasColumnName("off_market_date");

                    b.Property<int?>("OpenHouseCount")
                        .HasColumnName("open_house_count");

                    b.Property<DateTime?>("OpenHouseDatePublic")
                        .HasColumnName("open_house_date_public");

                    b.Property<string>("OpenHouseTimePublic")
                        .HasColumnName("open_house_time_public");

                    b.Property<string>("OpenHouseUpcoming")
                        .HasColumnName("open_house_upcoming");

                    b.Property<DateTime?>("OriginalEntryTimestamp")
                        .HasColumnName("original_entry_timestamp");

                    b.Property<decimal?>("OriginalListPrice")
                        .HasColumnName("original_list_price");

                    b.Property<string>("OutdoorLivingFeatures")
                        .HasColumnName("outdoor_living_features");

                    b.Property<string>("OutofAreaCity")
                        .HasColumnName("out_of_area_city");

                    b.Property<string>("OutofAreaCounty")
                        .HasColumnName("out_of_area_county");

                    b.Property<string>("OutofAreaSchoolDistrict")
                        .HasColumnName("out_of_area_school_district");

                    b.Property<string>("OwnershipType")
                        .HasColumnName("ownership_type");

                    b.Property<string>("ParcelNumber")
                        .HasColumnName("parcel_number");

                    b.Property<string>("ParkingFeatures")
                        .HasColumnName("parking_features");

                    b.Property<DateTime?>("PendingDate")
                        .HasColumnName("pending_date");

                    b.Property<bool?>("PermitInternetYN")
                        .HasColumnName("permit_internet_yn");

                    b.Property<int?>("PhotoCount")
                        .HasColumnName("photo_count");

                    b.Property<string>("PhotoExist")
                        .HasColumnName("photo_exist");

                    b.Property<DateTime?>("PhotoModificationTimestamp")
                        .HasColumnName("photo_modification_timestamp");

                    b.Property<string>("PoolDescronProp")
                        .HasColumnName("pool_descr_on_prop");

                    b.Property<bool?>("PoolonProperty")
                        .HasColumnName("pool_on_property");

                    b.Property<string>("PostalCode")
                        .HasColumnName("postal_code");

                    b.Property<string>("PostalCodePlus4")
                        .HasColumnName("postal_code_plus4");

                    b.Property<DateTime?>("PriceChangeTimestamp")
                        .HasColumnName("price_change_timestamp");

                    b.Property<bool?>("PropertyAddressonInternet")
                        .HasColumnName("property_address_on_internet");

                    b.Property<string>("PropertyConditionatSale")
                        .HasColumnName("property_condition_at_sale");

                    b.Property<string>("PropertySubType")
                        .HasColumnName("property_sub_type");

                    b.Property<string>("PropertyType")
                        .HasColumnName("property_type");

                    b.Property<int?>("ProviderKey")
                        .HasColumnName("provider_key");

                    b.Property<string>("PublicRemarks")
                        .HasColumnName("public_remarks");

                    b.Property<decimal?>("RATIO_ClosePrice_By_ListPrice")
                        .HasColumnName("ratio_close_price_by_list_price");

                    b.Property<decimal?>("RATIO_ClosePrice_By_OriginalListPrice")
                        .HasColumnName("ratio_close_price_by_original_list_price");

                    b.Property<decimal?>("RATIO_ClosePrice_By_SQFT")
                        .HasColumnName("ratio_close_price_by_sqft");

                    b.Property<decimal?>("RATIO_CurrentPrice_By_SQFT")
                        .HasColumnName("ratio_current_price_by_sqft");

                    b.Property<decimal?>("RATIO_ListPrice_By_SQFT")
                        .HasColumnName("ratio_list_price_by_sqft");

                    b.Property<string>("RatingAchieved")
                        .HasColumnName("rating_achieved");

                    b.Property<int?>("RatingYear")
                        .HasColumnName("rating_year");

                    b.Property<string>("Region")
                        .HasColumnName("region");

                    b.Property<int?>("RepairsAmount")
                        .HasColumnName("repairs_amount");

                    b.Property<string>("ReqdDocAgentInfor")
                        .HasColumnName("reqd_doc_agent_infor");

                    b.Property<string>("Restrictions")
                        .HasColumnName("restrictions");

                    b.Property<bool?>("RestrictionsYN")
                        .HasColumnName("restrictions_yn");

                    b.Property<string>("Roof")
                        .HasColumnName("roof");

                    b.Property<string>("Rooms")
                        .HasColumnName("rooms");

                    b.Property<string>("SalesRestrictions")
                        .HasColumnName("sales_restrictions");

                    b.Property<string>("SchoolDistrict")
                        .HasColumnName("school_district");

                    b.Property<DateTime?>("SearchExpireDate")
                        .HasColumnName("search_expire_date");

                    b.Property<string>("SellingAgentDirectWorkPhone")
                        .HasColumnName("selling_agent_direct_work_phone");

                    b.Property<string>("SellingAgentFullName")
                        .HasColumnName("selling_agent_full_name");

                    b.Property<string>("SellingAgentMLSID")
                        .HasColumnName("selling_agent_mls_id");

                    b.Property<long?>("SellingAgent_MUI")
                        .HasColumnName("selling_agent_mui");

                    b.Property<string>("SellingOfficeMLSID")
                        .HasColumnName("selling_office_mls_id");

                    b.Property<string>("SellingOfficeName")
                        .HasColumnName("selling_office_name");

                    b.Property<string>("SellingOfficePhone")
                        .HasColumnName("selling_office_phone");

                    b.Property<long?>("SellingOffice_MUI")
                        .HasColumnName("selling_office_mui");

                    b.Property<string>("SeniorHighSchool")
                        .HasColumnName("senior_high_school");

                    b.Property<string>("Sewer")
                        .HasColumnName("sewer");

                    b.Property<string>("SoldTerms")
                        .HasColumnName("sold_terms");

                    b.Property<string>("SpaHotTubDescription")
                        .HasColumnName("spa_hot_tub_description");

                    b.Property<bool?>("SpaHotTubYN")
                        .HasColumnName("spa_hot_tub_yn");

                    b.Property<bool?>("SprinklerSystem")
                        .HasColumnName("sprinkler_system");

                    b.Property<int?>("SqftTotal")
                        .HasColumnName("sqft_total");

                    b.Property<string>("SquareFootSource")
                        .HasColumnName("square_foot_source");

                    b.Property<string>("SrHighOther")
                        .HasColumnName("sr_high_other");

                    b.Property<string>("StateOrProvince")
                        .HasColumnName("state_or_province");

                    b.Property<string>("Status")
                        .HasColumnName("status");

                    b.Property<DateTime?>("StatusChangeTimestamp")
                        .HasColumnName("status_change_timestamp");

                    b.Property<DateTime?>("StatusContractualSearchDate")
                        .HasColumnName("status_contractual_search_date");

                    b.Property<string>("Steps")
                        .HasColumnName("steps");

                    b.Property<string>("StoriesLookup")
                        .HasColumnName("stories_lookup");

                    b.Property<string>("StreetDirPrefix")
                        .HasColumnName("street_dir_prefix");

                    b.Property<string>("StreetDirSuffix")
                        .HasColumnName("street_dir_suffix");

                    b.Property<string>("StreetName")
                        .HasColumnName("street_name");

                    b.Property<string>("StreetNumber")
                        .HasColumnName("street_number");

                    b.Property<string>("StreetSuffix")
                        .HasColumnName("street_suffix");

                    b.Property<string>("SubdivisionName")
                        .HasColumnName("subdivision_name");

                    b.Property<decimal?>("TaxAmount")
                        .HasColumnName("tax_amount");

                    b.Property<string>("TaxBlock")
                        .HasColumnName("tax_block");

                    b.Property<int?>("TaxFilledSqftTotal")
                        .HasColumnName("tax_filled_sqft_total");

                    b.Property<string>("TaxLot")
                        .HasColumnName("tax_lot");

                    b.Property<decimal?>("TaxRate")
                        .HasColumnName("tax_rate");

                    b.Property<int?>("TaxYear")
                        .HasColumnName("tax_year");

                    b.Property<DateTime?>("TempOffMarketDate")
                        .HasColumnName("temp_off_market_date");

                    b.Property<DateTime?>("TentativeCloseDate")
                        .HasColumnName("tentative_close_date");

                    b.Property<string>("Title")
                        .HasColumnName("title");

                    b.Property<string>("TitleCompany")
                        .HasColumnName("title_company");

                    b.Property<string>("Trees")
                        .HasColumnName("trees");

                    b.Property<int?>("UnitCount")
                        .HasColumnName("unit_count");

                    b.Property<string>("UnitNumber")
                        .HasColumnName("unit_number");

                    b.Property<string>("UnitStyle")
                        .HasColumnName("unit_style");

                    b.Property<string>("UpgradedEEFeatures")
                        .HasColumnName("upgraded_ee_features");

                    b.Property<bool?>("UpgradedEnergyEfficient")
                        .HasColumnName("upgraded_energy_efficient");

                    b.Property<string>("Utilities")
                        .HasColumnName("utilities");

                    b.Property<string>("VideoTourLinkBranded")
                        .HasColumnName("video_tour_link_branded");

                    b.Property<string>("VideoTourLinkUnbranded")
                        .HasColumnName("video_tour_link_unbranded");

                    b.Property<string>("View")
                        .HasColumnName("view");

                    b.Property<string>("VirtualTourLinkBranded")
                        .HasColumnName("virtual_tour_link_branded");

                    b.Property<string>("VirtualTourURLUnbranded")
                        .HasColumnName("virtual_tour_url_unbranded");

                    b.Property<bool?>("WaterAccess")
                        .HasColumnName("water_access");

                    b.Property<string>("WaterAccessDescription")
                        .HasColumnName("water_access_description");

                    b.Property<string>("WaterSource")
                        .HasColumnName("water_source");

                    b.Property<bool?>("Waterfront")
                        .HasColumnName("waterfront");

                    b.Property<string>("WaterfrontDescription")
                        .HasColumnName("waterfront_description");

                    b.Property<DateTime?>("WithdrawnDate")
                        .HasColumnName("withdrawn_date");

                    b.Property<int?>("YearBuilt")
                        .HasColumnName("year_built");

                    b.Property<string>("YearBuiltException")
                        .HasColumnName("year_built_exception");

                    b.HasKey("Matrix_Unique_ID");

                    b.ToTable("residential_properties");
                });
#pragma warning restore 612, 618
        }
    }
}
